from pathlib import Path

app_code = full
app_path = Path("/mnt/data/app_supabase.py")
app_path.write_text(app_code, encoding="utf-8")

schema_sql = r"""
-- ============================================================
-- Supabase schema for Academic Manager Portfolio & Teacher KPI
-- Review Dashboard
-- Run this in Supabase SQL Editor before deploying the Streamlit app.
-- ============================================================

create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- 1. Master session/activity logs
-- ------------------------------------------------------------
create table if not exists public.master_session_logs (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    "FullName" text not null,
    "Institution" text not null,
    "Grade" text default '',
    "Subject" text default '',
    "Book" text default '',
    "StartTime" timestamptz,
    "Duration_Min" double precision not null default 0,
    "Duration (HH:MM:SS)" text,
    "Duration (Minutes)" double precision,
    "Type" text not null default 'Other',
    "Voice_Note_Link" text,
    "Video_Evidence_1" text,
    "Video_Evidence_2" text,
    "Video_Evidence_3" text,
    "Writing_Sample_Link" text,
    "Assessment_Score_Pct" double precision,
    session_signature text not null unique,
    source text default 'user_metrics_upload',
    submission_signature text,
    created_at timestamptz not null default now()
);

create index if not exists idx_master_institution
    on public.master_session_logs ("Institution");

create index if not exists idx_master_fullname
    on public.master_session_logs ("FullName");

create index if not exists idx_master_starttime
    on public.master_session_logs ("StartTime");

create index if not exists idx_master_type
    on public.master_session_logs ("Type");

-- ------------------------------------------------------------
-- 2. Teacher/user roster
-- ------------------------------------------------------------
create table if not exists public.user_metrics (
    id bigint generated by default as identity primary key,
    "FirstName" text,
    "LastName" text,
    "FullName" text not null,
    "Institution" text not null,
    "Grade" text default '',
    "Subject" text default '',
    user_signature text not null unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_user_metrics_school
    on public.user_metrics ("Institution");

create index if not exists idx_user_metrics_teacher
    on public.user_metrics ("FullName");

-- ------------------------------------------------------------
-- 3. Teacher submissions / qualitative evidence
-- ------------------------------------------------------------
create table if not exists public.teacher_submissions (
    id bigint generated by default as identity primary key,
    teacher_name text not null,
    school text not null,
    submission_date date not null,
    grade text default '',
    subject text default '',
    book text default '',
    lesson_minutes double precision not null default 0,
    library_minutes double precision not null default 0,
    voice_note_link text,
    video_activity_link text,
    writing_sample_link text,
    assessment_score_pct double precision,
    submission_signature text not null unique,
    submitted_at timestamptz not null default now()
);

create index if not exists idx_teacher_submissions_teacher_date
    on public.teacher_submissions (teacher_name, submission_date);

-- ------------------------------------------------------------
-- 4. Updated-at trigger for user_metrics
-- ------------------------------------------------------------
create or replace function public.set_user_metrics_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_user_metrics_updated_at
on public.user_metrics;

create trigger trg_user_metrics_updated_at
before update on public.user_metrics
for each row
execute function public.set_user_metrics_updated_at();

-- ------------------------------------------------------------
-- 5. Atomic teacher submission RPC
-- ------------------------------------------------------------
create or replace function public.submit_teacher_submission(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_signature text;
    v_submission_id bigint;
    v_start_time timestamptz;
begin
    v_signature := payload->>'submission_signature';

    if v_signature is null or length(trim(v_signature)) = 0 then
        raise exception 'submission_signature is required';
    end if;

    -- Database-level duplicate protection.
    select id
    into v_submission_id
    from public.teacher_submissions
    where submission_signature = v_signature
    limit 1;

    if v_submission_id is not null then
        return jsonb_build_object(
            'success', false,
            'duplicate', true,
            'submission_id', v_submission_id
        );
    end if;

    insert into public.teacher_submissions (
        teacher_name,
        school,
        submission_date,
        grade,
        subject,
        book,
        lesson_minutes,
        library_minutes,
        voice_note_link,
        video_activity_link,
        writing_sample_link,
        assessment_score_pct,
        submission_signature
    )
    values (
        payload->>'teacher_name',
        payload->>'school',
        (payload->>'submission_date')::date,
        coalesce(payload->>'grade', ''),
        coalesce(payload->>'subject', ''),
        coalesce(payload->>'book', ''),
        coalesce((payload->>'lesson_minutes')::double precision, 0),
        coalesce((payload->>'library_minutes')::double precision, 0),
        nullif(payload->>'voice_note_link', ''),
        nullif(payload->>'video_activity_link', ''),
        nullif(payload->>'writing_sample_link', ''),
        case
            when payload->>'assessment_score_pct' is null
                 or payload->>'assessment_score_pct' = '' then null
            else (payload->>'assessment_score_pct')::double precision
        end,
        v_signature
    )
    returning id into v_submission_id;

    -- A stable timestamp makes the existing dashboard's date/week logic work
    -- while preserving the teacher's selected submission date.
    v_start_time :=
        (payload->>'submission_date')::date::timestamp
        + interval '12 hours';

    -- Mirror lesson-prep usage.
    insert into public.master_session_logs (
        "FullName",
        "Institution",
        "Grade",
        "Subject",
        "Book",
        "StartTime",
        "Duration_Min",
        "Type",
        "Voice_Note_Link",
        "Video_Evidence_1",
        "Writing_Sample_Link",
        "Assessment_Score_Pct",
        session_signature,
        source,
        submission_signature
    )
    values (
        payload->>'teacher_name',
        payload->>'school',
        coalesce(payload->>'grade', ''),
        coalesce(payload->>'subject', ''),
        coalesce(payload->>'book', ''),
        v_start_time,
        coalesce((payload->>'lesson_minutes')::double precision, 0),
        'lessonDelivery',
        nullif(payload->>'voice_note_link', ''),
        nullif(payload->>'video_activity_link', ''),
        nullif(payload->>'writing_sample_link', ''),
        case
            when payload->>'assessment_score_pct' is null
                 or payload->>'assessment_score_pct' = '' then null
            else (payload->>'assessment_score_pct')::double precision
        end,
        encode(
            digest(
                concat(
                    lower(trim(payload->>'school')), '|',
                    lower(trim(payload->>'teacher_name')), '|',
                    v_start_time::text, '|',
                    'lessonDelivery', '|',
                    lower(trim(coalesce(payload->>'book', ''))), '|',
                    lower(trim(coalesce(payload->>'grade', ''))), '|',
                    lower(trim(coalesce(payload->>'subject', ''))), '|',
                    to_char(
                        coalesce((payload->>'lesson_minutes')::double precision, 0),
                        'FM999999990.0000'
                    )
                ),
                'sha256'
            ),
            'hex'
        ),
        'teacher_submission_portal',
        v_signature
    )
    on conflict (session_signature) do nothing;

    -- Mirror library usage.
    insert into public.master_session_logs (
        "FullName",
        "Institution",
        "Grade",
        "Subject",
        "Book",
        "StartTime",
        "Duration_Min",
        "Type",
        "Voice_Note_Link",
        "Video_Evidence_1",
        "Writing_Sample_Link",
        "Assessment_Score_Pct",
        session_signature,
        source,
        submission_signature
    )
    values (
        payload->>'teacher_name',
        payload->>'school',
        coalesce(payload->>'grade', ''),
        coalesce(payload->>'subject', ''),
        coalesce(payload->>'book', ''),
        v_start_time,
        coalesce((payload->>'library_minutes')::double precision, 0),
        'library',
        nullif(payload->>'voice_note_link', ''),
        nullif(payload->>'video_activity_link', ''),
        nullif(payload->>'writing_sample_link', ''),
        case
            when payload->>'assessment_score_pct' is null
                 or payload->>'assessment_score_pct' = '' then null
            else (payload->>'assessment_score_pct')::double precision
        end,
        encode(
            digest(
                concat(
                    lower(trim(payload->>'school')), '|',
                    lower(trim(payload->>'teacher_name')), '|',
                    v_start_time::text, '|',
                    'library', '|',
                    lower(trim(coalesce(payload->>'book', ''))), '|',
                    lower(trim(coalesce(payload->>'grade', ''))), '|',
                    lower(trim(coalesce(payload->>'subject', ''))), '|',
                    to_char(
                        coalesce((payload->>'library_minutes')::double precision, 0),
                        'FM999999990.0000'
                    )
                ),
                'sha256'
            ),
            'hex'
        ),
        'teacher_submission_portal',
        v_signature
    )
    on conflict (session_signature) do nothing;

    return jsonb_build_object(
        'success', true,
        'duplicate', false,
        'submission_id', v_submission_id
    );
end;
$$;

-- ------------------------------------------------------------
-- 6. API/RLS notes
-- ------------------------------------------------------------
-- The Streamlit app reads the key only from server-side Streamlit secrets.
-- If you use the anon key, create explicit RLS policies appropriate to your
-- organization's access model. If you use the service-role key, NEVER expose
-- it to browser JavaScript or commit it to source control.

alter table public.master_session_logs enable row level security;
alter table public.user_metrics enable row level security;
alter table public.teacher_submissions enable row level security;

-- Example policies for an internal Streamlit app using the anon key.
-- Tighten these further if the application is publicly accessible.

drop policy if exists "dashboard read master sessions"
on public.master_session_logs;
create policy "dashboard read master sessions"
on public.master_session_logs
for select
to anon, authenticated
using (true);

drop policy if exists "dashboard insert master sessions"
on public.master_session_logs;
create policy "dashboard insert master sessions"
on public.master_session_logs
for insert
to anon, authenticated
with check (true);

drop policy if exists "dashboard update master sessions"
on public.master_session_logs;
create policy "dashboard update master sessions"
on public.master_session_logs
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "dashboard read user metrics"
on public.user_metrics;
create policy "dashboard read user metrics"
on public.user_metrics
for select
to anon, authenticated
using (true);

drop policy if exists "dashboard insert user metrics"
on public.user_metrics;
create policy "dashboard insert user metrics"
on public.user_metrics
for insert
to anon, authenticated
with check (true);

drop policy if exists "dashboard update user metrics"
on public.user_metrics;
create policy "dashboard update user metrics"
on public.user_metrics
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "dashboard read submissions"
on public.teacher_submissions;
create policy "dashboard read submissions"
on public.teacher_submissions
for select
to anon, authenticated
using (true);

-- The RPC is security-definer, so grant only execution; it performs the
-- transaction server-side.
revoke all on function public.submit_teacher_submission(jsonb)
from public;

grant execute on function public.submit_teacher_submission(jsonb)
to anon, authenticated;
"""

schema_path = Path("/mnt/data/supabase_schema.sql")
schema_path.write_text(schema_sql.strip() + "\n", encoding="utf-8")

requirements = """streamlit>=1.36
pandas>=2.1
numpy>=1.26
plotly>=5.20
reportlab>=4.0
openpyxl>=3.1
supabase>=2.5
"""
req_path = Path("/mnt/data/requirements.txt")
req_path.write_text(requirements, encoding="utf-8")

print(f"Created: {app_path}")
print(f"Created: {schema_path}")
print(f"Created: {req_path}")
